"
I store metadata for the OpenPonk-UML-Profiles package. This package provides infrastructure and builder utilities for defining, constructing, and managing custom UML profiles and stereotypes within OpenPonk models.
"
Class {
	#name : 'ManifestOpenPonkUMLProfiles',
	#superclass : 'PackageManifest',
	#category : 'OpenPonk-UML-Profiles-Manifest',
	#package : 'OpenPonk-UML-Profiles',
	#tag : 'Manifest'
}
